[package]
name = "exbawks-core"
description = "Emulator composition and boot planning for Exbawks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
exbawks-cpu.workspace = true
exbawks-debug.workspace = true
exbawks-gpu.workspace = true
exbawks-jit.workspace = true
exbawks-kernel.workspace = true
exbawks-memory.workspace = true
exbawks-types.workspace = true
exbawks-usb.workspace = true
exbawks-whp.workspace = true
exbawks-xbe.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
