#!/usr/bin/env python3
"""Generate the kernel export ordinal table from the vendored nxdk def file.

Source: crates/exbawks-kernel/data/xboxkrnl.exe.def (nxdk project, CC0-1.0).
Output: crates/exbawks-kernel/src/ordinals.rs

Decoration decode rules:
- ``Name@N``  is stdcall; the callee pops ``N`` argument bytes.
- ``@Name@N`` is fastcall; ``N`` counts bytes passed in ECX and EDX first,
  so the callee pops ``max(0, N - 8)`` stack bytes.
- An undecorated name is cdecl; the caller pops, so the gate pops zero.
- A ``DATA`` suffix marks a variable export with no calling convention.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEF_PATH = REPO_ROOT / "crates" / "exbawks-kernel" / "data" / "xboxkrnl.exe.def"
OUT_PATH = REPO_ROOT / "crates" / "exbawks-kernel" / "src" / "ordinals.rs"

EXPORT_LINE = re.compile(r"^\s*(\S+)\s+@\s*(\d+)\s+NONAME(\s+DATA)?\s*$")

HEADER = '''\
//! The kernel export ordinal table.
//!
//! Generated by `scripts/make-kernel-ordinals.py` from the vendored
//! `data/xboxkrnl.exe.def` (nxdk project, CC0-1.0). Do not edit by hand;
//! regenerate after any def-file change and commit both files together.

/// The linkage kind of one kernel export.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportKind {
    /// A callable function export dispatched through a gate.
    Function,
    /// A variable export read through the patched thunk slot.
    Data,
}

/// The calling convention of one function export.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CallingConvention {
    /// The callee pops `stack_bytes` argument bytes.
    Stdcall,
    /// ECX and EDX carry the first argument bytes; the callee pops the rest.
    Fastcall,
    /// The caller pops every argument.
    Cdecl,
}

/// One verified kernel export record.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KernelOrdinalInfo {
    /// The export ordinal.
    pub ordinal: u16,
    /// The undecorated export name.
    pub name: &'static str,
    /// The linkage kind.
    pub kind: ExportKind,
    /// The calling convention of function exports.
    pub convention: Option<CallingConvention>,
    /// The argument bytes a dispatch gate pops after the call.
    pub stack_bytes: u16,
}

const fn stdcall(ordinal: u16, name: &'static str, stack_bytes: u16) -> KernelOrdinalInfo {
    KernelOrdinalInfo {
        ordinal,
        name,
        kind: ExportKind::Function,
        convention: Some(CallingConvention::Stdcall),
        stack_bytes,
    }
}

const fn fastcall(ordinal: u16, name: &'static str, stack_bytes: u16) -> KernelOrdinalInfo {
    KernelOrdinalInfo {
        ordinal,
        name,
        kind: ExportKind::Function,
        convention: Some(CallingConvention::Fastcall),
        stack_bytes,
    }
}

const fn cdecl(ordinal: u16, name: &'static str) -> KernelOrdinalInfo {
    KernelOrdinalInfo {
        ordinal,
        name,
        kind: ExportKind::Function,
        convention: Some(CallingConvention::Cdecl),
        stack_bytes: 0,
    }
}

const fn data(ordinal: u16, name: &'static str) -> KernelOrdinalInfo {
    KernelOrdinalInfo { ordinal, name, kind: ExportKind::Data, convention: None, stack_bytes: 0 }
}

/// Every kernel export ordinal, sorted ascending.
pub const KERNEL_ORDINALS: &[KernelOrdinalInfo] = &[
'''

FOOTER = '''\
];

/// Looks up one export record by ordinal.
#[must_use]
pub fn kernel_ordinal_info(ordinal: u16) -> Option<&'static KernelOrdinalInfo> {
    KERNEL_ORDINALS
        .binary_search_by_key(&ordinal, |entry| entry.ordinal)
        .ok()
        .map(|index| &KERNEL_ORDINALS[index])
}
'''


def parse_def(path: Path) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []
    seen: set[int] = set()
    in_exports = False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split(";", 1)[0].rstrip()
        if not line.strip():
            continue
        if line.strip() == "EXPORTS":
            in_exports = True
            continue
        if not in_exports:
            continue
        match = EXPORT_LINE.match(line)
        if match is None:
            raise SystemExit(f"unparsed export line: {line!r}")
        decorated, ordinal_text, data_flag = match.groups()
        ordinal = int(ordinal_text)
        if ordinal in seen or not 0 < ordinal <= 0xFFFF:
            raise SystemExit(f"bad or duplicate ordinal: {line!r}")
        seen.add(ordinal)
        entries.append((ordinal, render_entry(decorated, ordinal, bool(data_flag))))
    entries.sort(key=lambda entry: entry[0])
    return entries


def render_entry(decorated: str, ordinal: int, is_data: bool) -> str:
    if is_data:
        if "@" in decorated:
            raise SystemExit(f"decorated DATA export: {decorated!r}")
        return f'    data({ordinal}, "{decorated}"),'
    if decorated.startswith("@"):
        name, _, byte_text = decorated[1:].rpartition("@")
        stack = max(0, int(byte_text) - 8)
        return f'    fastcall({ordinal}, "{name}", {stack}),'
    if "@" in decorated:
        name, _, byte_text = decorated.rpartition("@")
        return f'    stdcall({ordinal}, "{name}", {int(byte_text)}),'
    return f'    cdecl({ordinal}, "{decorated}"),'


def main() -> int:
    entries = parse_def(DEF_PATH)
    body = "\n".join(text for _, text in entries)
    OUT_PATH.write_text(HEADER + body + "\n" + FOOTER, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} with {len(entries)} exports")
    return 0


if __name__ == "__main__":
    sys.exit(main())
